### ISSUE TITLE
Working with SF4

### ISSUE THREAD

**Issue by vince83110** [rewieer/TaskSchedulerBundle#1]
I tried to install your bundle using SF4, I used composer, then added this in my config/bundles.php :

`Rewieer\TaskSchedulerBundle\RewieerTaskSchedulerBundle::class => ['all' => true],`

But when I try the command  : `php bin\console ts:run`

I got this error :  

> There are no commands defined in the "ts" namespace.

Do I need to do something more to get it working with SF4 ? Thanks.

**Comment by faysh** [comment]
I don't know how correct is this solution, but you must register needed commands of this bundle on your services.yaml. I add two service like this:
`    ts.run:
        class: Rewieer\TaskSchedulerBundle\Command\RunCommand
        tags:
          - { name: console.command }

    ts.list:
        class: Rewieer\TaskSchedulerBundle\Command\ListCommand
        tags:
          - { name: console.command }
`

I hope this fix you problem)

**Comment by Rewieer** [comment]
Hello, thanks for your insights
I didn't worked this out on SF4 so far but I expected some registering problems of the sort. I'll check out what I can do to make this works for SF4 and for SF3 :)

**Comment by rewieer** [comment]
Fixed in #e6d0101
