### ISSUE TITLE
Unexpected schedule behaviour

### ISSUE THREAD

**Issue by paha77** [rewieer/TaskSchedulerBundle#12]
I want to run a task hourly.  If I configure the $schedule like this in initialize() function of my implementation, the task is always (minutely) executed:

```php
    protected function initialize(Schedule $schedule)
    {
        $schedule
            ->minutes(0)
            ->everyHours()
        ;
    }
```
```php
var_dump($schedule->getExpression());
```
outputs:

`string(9) "0 * * * *"`

which is a valid cron definition (see: https://crontab.guru/#0_*_*_*_*)

After longer debugging I've found that in [Task/Schedule.php](https://github.com/rewieer/TaskSchedulerBundle/blob/master/Task/Schedule.php#L55) the variable is passed as an integer but [dragonmantank/cron-expression's CronExpression](https://github.com/dragonmantank/cron-expression/blob/v2.3.0/src/Cron/CronExpression.php#L152) expects a string (in 2.3 it's only a PHPDOC annotation but in the master already a type hint).

If I change the affected line to

```php
$this->cron->setPart(0, (string)$minutes);
```

It works as expected.

**Comment by paha77** [comment]
> Hey @paha77 thanks for the issue. Can you submit a PR ? I'm not working in PHP currently, and havn't been for awhile.

Done. :)

**Comment by rewieer** [comment]
Merged !
