### ISSUE TITLE
Documentation induces in error

### ISSUE THREAD

**Issue by Zasco** [rewieer/TaskSchedulerBundle#2]
Documentation says to use ts:run 1, but this calls the task ID n°1 with no regard of it's schedule and instead rely on the associated CRON recurrency. I get this may be the desired feature, but it isn't clear. It should be clearly mentionned that to use the scheduler, which is in my sense the default behaviour, no id should be provided. Documentation should hence be adjusted accordingly.

**Comment by rewieer** [comment]
You are talking about the documentation of ts:run ? Indeed in the code the ID parameter is optional, I thought it was enough for the console helper to print that no ID can be provided in order to run every task (if they are due).

I'd be happy to accept your PR on this !

**Comment by Zasco** [comment]
Here you go [#3]. Hope it fits your requirements.

**Comment by rewieer** [comment]
Yep, thanks for your PR!
