### ISSUE TITLE
class dummy kernel extends nothing

### ISSUE THREAD

**Issue by marcin-derlukiewicz** [rewieer/TaskSchedulerBundle#22]
https://github.com/rewieer/TaskSchedulerBundle/blob/c3c936823743ff4e1e2bf4ef16b5c2d63842c09d/Tests/DependencyInjection/DummyKernel.php#L15

**Comment by marcin-derlukiewicz** [comment]
is this class even needed?

**Comment by NicoHaase** [comment]
If everything is working without that class, feel free to remove it

**Comment by marcin-derlukiewicz** [comment]
tests are working... this class is there since initial commit, i suppose it should be removed but maybe @rewieer do you remeber what it was for?

**Comment by rewieer** [comment]
@marcin-derlukiewicz I don't have the slightest clue to be honest. It's probably part of an idea that I finally didn't implement concerning tests.

**Comment by marcin-derlukiewicz** [comment]
it was dropped in pr #23
