### ISSUE TITLE
everyX optional parameter provided before required one

### ISSUE THREAD

**Issue by marcin-derlukiewicz** [rewieer/TaskSchedulerBundle#24]
https://github.com/rewieer/TaskSchedulerBundle/blob/c3c936823743ff4e1e2bf4ef16b5c2d63842c09d/Task/Schedule.php#L85

**Comment by marcin-derlukiewicz** [comment]
also $time should be type hinted

**Comment by NicoHaase** [comment]
Thank you for fixing this in #26
