### ISSUE TITLE
EveryMinutes should use static CronExpression::MINUTE instead of int value

### ISSUE THREAD

**Issue by marcin-derlukiewicz** [rewieer/TaskSchedulerBundle#25]
https://github.com/rewieer/TaskSchedulerBundle/blob/c3c936823743ff4e1e2bf4ef16b5c2d63842c09d/Task/Schedule.php#L74

https://github.com/rewieer/TaskSchedulerBundle/blob/c3c936823743ff4e1e2bf4ef16b5c2d63842c09d/Task/Schedule.php#L65

**Comment by NicoHaase** [comment]
Resolved through #26
