### ISSUE TITLE
php8 support

### ISSUE THREAD

**Issue by marcin-derlukiewicz** [rewieer/TaskSchedulerBundle#27]
php8 is released, symfony supports it, could we add support for it?

**Comment by NicoHaase** [comment]
Feel free to test it :)

**Comment by marcin-derlukiewicz** [comment]
shouldn't you just add config for travis to test it?

**Comment by NicoHaase** [comment]
According to https://travis-ci.com/github/rewieer/TaskSchedulerBundle/builds/205478767, this looks surprisingly good. I'll test it in a productive project to see whether this really was that easy...

**Comment by marcin-derlukiewicz** [comment]
@NicoHaase any news regarding this?

**Comment by NicoHaase** [comment]
I'm sorry, but I could not test this in any of my projects yet, as most of them are still waiting for a Doctrine update or other packages to be fully compatible to PHP 8

**Comment by madmortigan1** [comment]
Hi, 
there is depcreated exception in the following file:
Task/Schedual.php
Line 85.

**PHP Deprecated:  Required parameter $part follows optional parameter $time in /var/www/html/vendor/rewieer/taskschedulerbundle/Task/Schedule.php on line 85**

Adding default null to $part is a quick fix for it

**Comment by NicoHaase** [comment]
@madmortigan1 this has already been fixed on master in #26

**Comment by NicoHaase** [comment]
@marcin-derlukiewicz thanks for your help getting this release out: this package supports PHP 8 from now on. I'd like to hear from you whether it works as it should, I could not spot any problems with simple tests
