### ISSUE TITLE
Error Call to a member function isDue() on null 

### ISSUE THREAD

**Issue by essteffan** [rewieer/TaskSchedulerBundle#33]
Hi. 
I have a service that extends  AbstractScheduledTask and methods initialize and run but i have this error:
In AbstractScheduledTask.php line 27:
                                             
  Call to a member function isDue() on null  

/**
     * @param Schedule $schedule
     */
    protected function initialize(Schedule $schedule)
    {
        $schedule
            ->everyMinutes($this->cronTime); // Perform the task every 15 minutes
    }

    /**
     * @return int
     */
    public function run()
    {
        return Process::fromShellCommandline('php bin/console supplier:load ' . $this->tagName)->run();
    }

Any help here?
Thanks!

**Comment by essteffan** [comment]
@rewieer Can you help me? From what is see the Scheduler Class checks for $task->isDue($currentTime) and in AbstractScheduledTask abstract class on line 27 $this->schedule is null and this returns the error

**Comment by essteffan** [comment]
This is the solution for my problem


rewieer commented 2 days ago
That's because you override the constructor and dont call the parent
constructor.
You have to call the parent constructor method using
`parent::__construct();`
I think we should fix this locally anyway, many people will fall into this
trap.

**Comment by NicoHaase** [comment]
If you are facing such problems again, please share the full details in the beginning. That helps to spot the problem
