### ISSUE TITLE
Documentation Update: Clarification

### ISSUE THREAD

**Issue by mikeyudin** [rewieer/TaskSchedulerBundle#34]
Hello,

Thank you for the work on the bundle.  It's very helpful.  I think it may be a good idea to specify in the documentation that if you're using the hours scheduling (`hours()`, `everyHours()`, `daily`), that they should also need to specify the `minutes()` accordingly.

Currently, if you specify `$schedule->everyHours(3)`, the job will run at every minute within the hours specified.  Users need to specify `$schedule->minutes(0)->everyHours(3)` to ensure it only runs once every 3 hours.  

Took a little time to figure that one out, and might help users going forward.

Thanks!

**Comment by rewieer** [comment]
Hello,
This is true and indeed a problem i've stumbled upon myself a few months ago. Would you like to submit a PR ?

**Comment by mikeyudin** [comment]
PR Created!
