### ISSUE TITLE
Hi, I don't see this cron running

### ISSUE THREAD

**Issue by essteffan** [rewieer/TaskSchedulerBundle#36]
I want to set a cron to run at 6AM and it doesn't run. I did something wrong?    

$schedule
            ->minutes(0)->hours(6)->daily();

**Comment by rewieer** [comment]
@essteffan do you override the constructor ?

**Comment by essteffan** [comment]
No, I extends AbstractScheduledTask and use methods initialize and run

  /**
     * @param Schedule $schedule
     */
    protected function initialize(Schedule $schedule)
    {
        $schedule
            ->minutes(0)->hours(6)->daily();
    }

    /**
     * @return int
     * @throws ValidationException
     */
    public function run()
    {}

**Comment by NicoHaase** [comment]
Can you share more details about this? What does `bin/console ts:list --show-run-dates`  print?

**Comment by essteffan** [comment]
In AbstractScheduledTask.php line 46:
                                               
  Call to a member function getCron() on null  
                                               

ts:list [--show-run-dates [SHOW-RUN-DATES]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>


Somehow the format is wrong?

**Comment by NicoHaase** [comment]
Please share more details, like the full content of your task

**Comment by essteffan** [comment]
Ok, so i have a Service which need to do a job, i can do it manually but i also created a cron to make it every morning at 6AM

So in service i've extended AbstractScheduledTask and implement those 2 methods initialize() and run()

If i do  bin/console ts:list  i see 

bin/console ts:list                 
+----+--------------------------------------------------------------------------+
| ID | Class                                                                    |
+----+--------------------------------------------------------------------------+
| 1  | App\Service\Folder\Service   |
| 2  | App\Service\Folder\Service2 |
+----+--------------------------------------------------------------------------+

If i do bin/console ts:list --show-run-dates, i get error In AbstractScheduledTask.php line 46:

Call to a member function getCron() on null

Thank you for your help

**Comment by rewieer** [comment]
That's because you override the constructor and dont call the parent
constructor.
You have to call the parent constructor method using
`parent::__construct();`
I think we should fix this locally anyway, many people will fall into this
trap.

**Comment by NicoHaase** [comment]
Sorry to be so picky, but please share more details - without seeing your code, it is really hard to provide help. Also, I don't think that this is a bug of this package

**Comment by essteffan** [comment]
@rewieer Thank you, it would be great to add that info into docs. it seems to work now, the response is :

Rewieer\TaskSchedulerBundle\Task\Schedule^ {#903
  -cron: Cron\CronExpression^ {#3813
    -cronParts: array:5 [
      0 => "0"
      1 => "6"
      2 => "*"
      3 => "*"
      4 => "*"
    ]
    -fieldFactory: Cron\FieldFactory^ {#3873
      -fields: array:5 [
        0 => Cron\MinutesField^ {#3814
          #rangeStart: 0
          #rangeEnd: 59
          #fullRange: array:60 [
            0 => 0
            1 => 1
            2 => 2
            3 => 3
            4 => 4
            5 => 5
            6 => 6
            7 => 7
            8 => 8
            9 => 9
            10 => 10
            11 => 11
            12 => 12
            13 => 13
            14 => 14
            15 => 15
            16 => 16
            17 => 17
            18 => 18
            19 => 19
            20 => 20
            21 => 21
            22 => 22
            23 => 23
            24 => 24
            25 => 25
            26 => 26
            27 => 27
            28 => 28
            29 => 29
            30 => 30
            31 => 31
            32 => 32
            33 => 33
            34 => 34
            35 => 35
            36 => 36
            37 => 37
            38 => 38
            39 => 39
            40 => 40
            41 => 41
            42 => 42
            43 => 43
            44 => 44
            45 => 45
            46 => 46
            47 => 47
            48 => 48
            49 => 49
            50 => 50
            51 => 51
            52 => 52
            53 => 53
            54 => 54
            55 => 55
            56 => 56
            57 => 57
            58 => 58
            59 => 59
          ]
          #literals: []
        }
        1 => Cron\HoursField^ {#3975
          #rangeStart: 0
          #rangeEnd: 23
          #fullRange: array:24 [
            0 => 0
            1 => 1
            2 => 2
            3 => 3
            4 => 4
            5 => 5
            6 => 6
            7 => 7
            8 => 8
            9 => 9
            10 => 10
            11 => 11
            12 => 12
            13 => 13
            14 => 14
            15 => 15
            16 => 16
            17 => 17
            18 => 18
            19 => 19
            20 => 20
            21 => 21
            22 => 22
            23 => 23
          ]
          #literals: []
        }
        2 => Cron\DayOfMonthField^ {#3973
          #rangeStart: 1
          #rangeEnd: 31
          #fullRange: array:31 [
            0 => 1
            1 => 2
            2 => 3
            3 => 4
            4 => 5
            5 => 6
            6 => 7
            7 => 8
            8 => 9
            9 => 10
            10 => 11
            11 => 12
            12 => 13
            13 => 14
            14 => 15
            15 => 16
            16 => 17
            17 => 18
            18 => 19
            19 => 20
            20 => 21
            21 => 22
            22 => 23
            23 => 24
            24 => 25
            25 => 26
            26 => 27
            27 => 28
            28 => 29
            29 => 30
            30 => 31
          ]
          #literals: []
        }
        3 => Cron\MonthField^ {#3971
          #rangeStart: 1
          #rangeEnd: 12
          #literals: array:12 [
            1 => "JAN"
            2 => "FEB"
            3 => "MAR"
            4 => "APR"
            5 => "MAY"
            6 => "JUN"
            7 => "JUL"
            8 => "AUG"
            9 => "SEP"
            10 => "OCT"
            11 => "NOV"
            12 => "DEC"
          ]
          #fullRange: array:12 [
            0 => 1
            1 => 2
            2 => 3
            3 => 4
            4 => 5
            5 => 6
            6 => 7
            7 => 8
            8 => 9
            9 => 10
            10 => 11
            11 => 12
          ]
        }
        4 => Cron\DayOfWeekField^ {#3976
          #rangeStart: 0
          #rangeEnd: 7
          #nthRange: array:5 [
            0 => 1
            1 => 2
            2 => 3
            3 => 4
            4 => 5
          ]
          #literals: array:7 [
            1 => "MON"
            2 => "TUE"
            3 => "WED"
            4 => "THU"
            5 => "FRI"
            6 => "SAT"
            7 => "SUN"
          ]
          #fullRange: array:8 [
            0 => 0
            1 => 1
            2 => 2
            3 => 3
            4 => 4
            5 => 5
            6 => 6
            7 => 7
          ]
        }
      ]
    }
    -maxIterationCount: 1000
  }
}

I will see if tomorrow the cron is triggered

also Thanks @NicoHaase for you help!

Best Regards

**Comment by essteffan** [comment]
It's working good now, thank you both!
