### ISSUE TITLE
everyX(1, CronExpression::WEEKDAY) does not work as expected

### ISSUE THREAD

**Issue by awawrowicz** [Rewieer/TaskSchedulerBundle#42]
I would expect that Schedule::everyX(1, CronExpression::WEEKDAY) schedules the task once a week on Monday but it does not.

**Comment by NicoHaase** [comment]
I've just checked the details: `Schedule::everyX(1, CronExpression::WEEKDAY)` does not correspond to "once a week on mondays", but to "every weekday" (see the documentation: Generic function to update a cron part as an "everyX" pattern such as "every 3 hours" or "every 10 minutes"). And as you haven't set any frequency for minutes, or hours, this defaults to "every minute, every hour"

**Comment by jogoool** [comment]
any example how to correctly set the schedule for weekly process, for example how to set schedule to run every sunday at one o'clock am.

**Comment by NicoHaase** [comment]
Have you tried using `$schedule->setExpression('0 1 * * 7')`?

**Comment by jogoool** [comment]
is this doing the same thing ?
 $schedule->minutes(0)->hours(1)->daysOfWeek(7);
