### ISSUE TITLE
Compatibility with Symfony 5

### ISSUE THREAD

**Issue by NicoHaase** [rewieer/TaskSchedulerBundle#8]
After upgrading Sf from 4.2 to 4.3, the following deprecation notices are given:

- A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0.
- The "Symfony\Component\Config\Definition\Builder\TreeBuilder::root()" method called for the "rewieer_task_scheduler" configuration is deprecated since Symfony 4.3, pass the root name to the constructor instead.
- The "Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand" class is deprecated since Symfony 4.2, use "Symfony\Component\Console\Command\Command" with dependency injection instead.
- The "Rewieer\TaskSchedulerBundle\Command\ListCommand" class extends "Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand" that is deprecated since Symfony 4.2, use {@see Command} instead.
- The "Rewieer\TaskSchedulerBundle\Command\RunCommand" class extends "Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand" that is deprecated since Symfony 4.2, use {@see Command} instead.

**Comment by rewieer** [comment]
Hello @NicoHaase !
I'm not working on Symfony anymore, so I don't have time these days to handle issues such as this one.
A PR would be most welcome !

**Comment by NicoHaase** [comment]
I'd be happy to help you out :)

**Comment by NicoHaase** [comment]
@rewieer thanks for merging - can you also sync that package to packagist.org, either through a manual sync or through enabling the hooking?

**Comment by rewieer** [comment]
Ah yeah, my bad, I thought autosync was on. It's fixed now !

**Comment by NicoHaase** [comment]
@rewieer thanks, that also works now. If you want to, you could open a Travis account such that the test suite is run from time to time. This is free for open-source projects as yours

**Comment by otakupahp** [comment]
Hello Nico and Rewieer, could you please also update documentation about how to use now the pack?

**Comment by NicoHaase** [comment]
I'd be happy to provide some more documentation, but if you are completely new to Symfony, I don't know where to start - do you have any specific problem?

**Comment by otakupahp** [comment]
What I achieved up to know:

 - Configured service.yaml but I do not know if it is ok (I used the code you added in another issue)
 - I created the Task class extending AbstractScheduledTask
 - I don't know how to test and debug that :(
